# Generated by Django 4.2.5 on 2023-09-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
