# Generated by Django 4.2.5 on 2023-09-19 13:54

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to=job.models.image_upload_name),
            preserve_default=False,
        ),
    ]
